/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Invisible(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/invisible.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Cloud_3002"
          castShadow
          receiveShadow
          geometry={nodes.Cloud_3002.geometry}
          material={materials.Cloud}
          position={[1.32, -2.56, 42.6]}
          rotation={[0, 0.72, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/invisible.glb");
